# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Arfi',
    'version': '1.1',
    'category': 'Human Resources',
    'sequence': 75,
    'summary': 'ARFI Management',
    'description': """
Arfi Management
==========================

    """,
    'website': 'https://www.odoo.com/page/employees',
    'images': [
    ],
    'depends': [ 'base','product','muk_dms', 'board'
    ],
    'data': [
        'security/arfi_security.xml',
        'security/ir.model.access.csv',
        
        'views/partner_view.xml',
        'views/arfi_view.xml',
        'views/product_view.xml',
        'views/commande_view.xml',
        'views/kks_view.xml',
        'views/plan_view.xml',
        'views/invoice_view.xml',
        'views/affaire_view.xml',
        'views/purchase_view.xml',
        'views/contract_view.xml',
        'views/report_invoice.xml',
        'wizard/product_import_view.xml',
        'wizard/product_import_image_view.xml',
        'wizard/product_order_customer_view.xml',
        'wizard/product_kks_search_wizard_view.xml',
        'wizard/product_kks_etat_wizard_view.xml',
        'wizard/product_kks_pid_wizard_view.xml',
        'wizard/product_kks_tarif_view.xml',
        'wizard/product_kks_piece_view.xml',
        'wizard/product_kks_stock_view.xml',
        'wizard/product_kks_pps_view.xml',
        'wizard/product_observation_view.xml',
        'wizard/product_template_information_view.xml',
        'wizard/product_template_procedure_view.xml',
        'wizard/product_template_nature_view.xml',
        'wizard/product_order_service_view.xml',
        'wizard/product_order_test_view.xml',
        'wizard/product_order_operation_view.xml',
        'wizard/product_piece_delete_view.xml',
        'wizard/product_attribute_delete_view.xml',
        'wizard/product_report_view.xml',
        'wizard/product_purchase_evaluation_wizard_view.xml',
        'wizard/product_purchase_etat_wizard_view.xml',
        'data/muk_dms_data_directory.xml',
        'data/muk_dms_data_root.xml',
        'data/muk_dms_data_file.xml',
        'data/ir_sequence_data.xml',
        'report/report_paperformat.xml',
        'report/arfi_reports.xml',
        'report/product_order_operation_report.xml',
        'report/product_order_devis_report.xml',
        'report/product_order_rapport_report.xml',
        'report/product_order_certificat_report.xml',
        'report/product_order_customer_report.xml',
        'report/product_kks_echafaudage_report.xml',
        'report/product_template_cartouche_report.xml',
        'report/product_template_outillage_report.xml',
        'report/product_kks_report_views.xml',
        'report/product_kks_pdr_report.xml',
        'report/product_kks_facture_report.xml',
        'report/product_kks_outillage_report.xml',
        'report/product_kks_pps_report.xml',
        'report/product_invoice_report.xml',
        'report/product_devis_report.xml',
        'report/product_affaire_report.xml',
        'report/product_purchase_report.xml',
        'report/product_bc_report.xml',
        'views/arfi_menu.xml',
        'views/arfi_templates.xml',
        
    ],
    'demo': [],
    'test': [
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'qweb' : [
        'static/src/xml/templates.xml'
    ],
}
